# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Gz1vxV-Rnviv4Brcj5F8OaPyUtVn0sR
"""

def register():
  username=input('Please enter your registered Email')
  for i in range(0,len(username)):
    if ((i==0 and username[i]=='@')or(username[i]=='@' and username[i+1]=='.')or(i==0 and username[i].isdigit())or(i==0 and (username[i]=='&' or username[i]=='!' or username[i]=='%' or username[i]=='#'))):
      print('Enter a valid username')
      register()
  password=input('Enter your password')
  digit=0
  special_char=0
  small_letters=0
  capital_letters=0
  for i in range(0,len(password)):
    if(password[i]=='!' or password[i]=='%' or password[i]=='#' or password[i]=='&' or password[i]=='@' ):
      special_char+=1
    if(password[i].isupper()):
      capital_letters+=1
    if(password[i].islower()):
      small_letters+=1
    if(password[i].isdigit()):
      digit+=1
  if((len(password)>5 and len(password)<16) and special_char>=1 and digit>=1 and small_letters>=1 and capital_letters>=1):
    print('Your Registration is completed sucessfully !!!')
    db=open("login.txt", "a")
    data=username+','+password
    db.write(data)
    db.write('\n')
    db.close()
    db=open("login.txt", "r")
    print(db.read())

  else:
    print('password is not matching please register again')
    register()


ss='false'
i=input('Welcome.\n if New User Please enter y to register else n')
if i=='y':
  register()
if i=='n':
  i=input('To Login? enter YES or NO?')
  if i=='n':
    print('NO ACTION TAKEN')
  if i=='y':
    user_name=input('Please Enter Your Email')
    pass_word=input('Please Enter your Password')
    db=open("login.txt", "r")

    for s in db:
      a,b=s.split(",")
      b=b.strip()
      if(user_name==a and pass_word==b):
        print('login successful!!')
        ss='true'
        exit()
      if(user_name==a and pass_word!=b):
        print('Your Password is Wrong')
        l=input('Click Forget Password. Enter Yes/No')
        if l=='y':
          print('New Password is ',b)
          ss='true'
          break
        else:
          print('No forget password is')
          ss='true'
          break
    if(ss=='false'):
      print('Credential Not Found.Kindly Register')